### ISSUE TITLE
Spare hd space

### ISSUE THREAD

**Issue by ReadyPlayer29** [Optiroc/AGSImager#62]
Could we have say 300mb of spare space on the sys and games hdd's, just been very handy to add stuff to as required

**Comment by Optiroc** [comment]
I'm not sure this is a good idea, since if users make a lot of customizations to the main HDF that someone else built for them they will probably be unwilling to update to newer builds.

The Saves drive is where extra "user data" is meant to go since it isn't meant to be replaced when updating the main HDF. For further more advanced customizations, users should rather make their own builds.
